language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - coverage run -m unittest

deploy:
  provider: pypi
  username: "__token__"
  secure:
      password: RdR9Bsb78VzD/nKDr3g1S3WfqT8AtEfMHDktUa11DZwndNuD7Kq1Zp59Nm1x5oQATuP7C8X79P+6rVPv14zRtzM4wnme4ig5+z9EQ2zHgUhSoT/mhBrvjGW3xqvJPQaw3Z73xf4J6V19pl+lbAEu36vD/Q6RLuBv/hi7CwQeSuBCOQ+6uEEn0TxQvGwJuWqSOfVIu9SAZFB3ZjgUi7aI2Y4jBX4FDrCMf75ERTViG9iMRHb4luTWz3O79c5CnMIKmhuKOPr2tAGBFXBWjiDnUHzaktWZLws5ukU9EPbZIeUZkvSQV+UeqN9Zai29J90Ysel405H8qLn0f2EX1t4qqmznnHfxGO96jryhhXRpqKUuLKhAyc7q5OZ76hCmBE8oFIZGeETyg0CjsnYWF0RTOvuwz/Cy8qxaRHbhjdlr40t+T97WwBb8/YEVwPjInGNV9nuiwyf6i8zjUSe670GaZ7oMw/XdnI/gktXdCp8H4aFUJF9tH44o76Rk3aVbqNNbMy6HdrnsKyO9ews53kTavDoZYMbAbMOEkhkN2xbQh1sHZM9xfSkbfR/BRmwJLPQ69wvVoFXldWnG9g7ITG5MTsyv/ugrSO5Zs0nalRHBaGPdtmIimH1QWfTJZPecSZ21575Kl0ECJ6C50qF2wRSuOHiBhPuK0XTUv5dT2h4GC7A=

notifications:
  email: false